version: '3'

services:
  web:
    build: .
    ports:
      - "8083:80" # Change this line to use port 8083 instead of 8082
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bonkers_login
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
